server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: "lb://USER-SERVICE"
          predicates:
            - Path=/api/v1/user/**
          filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/api/v1/user/(?<segment>.*), /$\{segment}

#        - id: user-service-post
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/v1/user/**
#            - Method=POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/api/v1/user/(?<segment>.*), /$\{segment}
#
#        - id: user-service-get
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/v1/user/**
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/api/v1/user/(?<segment>.*), /$\{segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
            - Method=POST, GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/product/(?<segment>.*), /$\{segment}
